### ISSUE TITLE
Plugin doesn't run with 2.0.1

### ISSUE THREAD

**Issue by JosephEoff** [JosephEoff/MuseScore_UltraStar_Exporter#1]
Version evaluation only works for the development version, not the released binaries from the musescore homepage.

**Comment by jeetee** [comment]
Plugin runs with 2.0.2 (current stable release), at least under Windows7

**Comment by JosephEoff** [comment]
Started on Windows with MuseScore 2.0.1 as well.
Closed after confirmation from jeetee
