### ISSUE TITLE
Handle mid-song BPM changes

### ISSUE THREAD

**Issue by jeetee** [JosephEoff/MuseScore_UltraStar_Exporter#13]
UltraStar format allows for mid-song BPM changes by having a line formatted as follows:

```
B tick bpm
```

[Performous parser section](https://github.com/performous/performous/blob/master/game/songparser-txt.cc#L95)

**Comment by jeetee** [comment]
I think this can be easily added, as it's simply checking for another annotation.

I'm also thinking about reworking the checkForMarker function and incorporating BPM checks in there. Currently we already loop through all annotations three times for each note (checkForMarker), with BPM support this would become 4 times.

The new approach would be a function that checks the annotations and returns a simple object along this format:

``` javascript
{
    tempo: null | value
    golden: true | false
    freestyle: true | false
    lineBreak: true | false
}
```

Any thoughts on your end about that approach?

**Comment by JosephEoff** [comment]
I didn't know about the BPM changes - the documentation I used didn't mention it.
I'll have a look-see at checkForMarker later, but I think it would be better to separate the marker check and the BPM check.

**Comment by JosephEoff** [comment]
Definitely separate methods.  
It doesn't matter that we're checking the annotations multiple times - there's almost never a StaffText, and when there is there's usually only one.
We'll leave checkForMarkerInStaffText as is and create two new methods:
hasBPMChange (segment)
getNewBPMFromSegment(segment)
hasBPMChange checks for a Element.TEMPO_TEXT in the annotations and returns true if there is one.
getNewBPMFromSegment gets the new tempo.
